### ISSUE TITLE
Add Dynamic GitHub Stars and Forks Button

### ISSUE THREAD

**Issue by vinitshahdeo** [vinitshahdeo/50DaysOfJavaScript#10]
Enhance the [#50DaysOfJavascript](https://50daysofjavascript.netlify.app/) website by adding a dynamic button that displays the current number of GitHub stars and forks for our project repository. This will provide visitors with real-time information about the popularity of our initiative.

- Add a visually appealing button with a recognizable GitHub icon. Refer to [react-github-buttons](https://vaibhavhrt.github.io/react-github-buttons/)
- Our project's GitHub repository: [Link to Repository](https://github.com/vinitshahdeo/50DaysOfJavaScript)
- Current website URL: [50daysofjavascript.netlify.app](https://50daysofjavascript.netlify.app/)
- Proposed location for the GitHub button: 

**Note**: Enhancing our website with this dynamic GitHub button will provide visitors with valuable insights into the project's popularity and encourage more community involvement.

Thank you for your contribution to improving the [#50DaysOfJavascript](https://50daysofjavascript.netlify.app/) website!

**Comment by lejara** [comment]
Hello!
May i work on this?

**Comment by vinitshahdeo** [comment]
@lejara Assigning this to you. @deeksharungta will help you with the reviews.

**Comment by lejara** [comment]
Where would you like the location for the button to be

**Comment by deeksharungta** [comment]
> Where would you like the location for the button to be

Place the button above the text #50DaysOfJavascript at the top and tailor its design to align with the website's theme.
