### ISSUE TITLE
TypoError in Google form:- Contest Start date is showing 20th jan 2023

### ISSUE THREAD

**Issue by prashantguptadev** [vinitshahdeo/50DaysOfJavaScript#3]
![Screenshot from 2023-01-29 20-35-31](https://user-images.githubusercontent.com/53941491/215335565-80638c8f-3e0a-4fd4-bea0-382b8fe6f5ea.png)

**Comment by vinitshahdeo** [comment]
Thanks for bringing this up—it's updated now! 🙏
